# Agent Coordination Configuration
# Defines how agents communicate and coordinate with each other

coordination_patterns:
  # Hierarchical coordination for complex workflows
  hierarchical:
    orchestrator_agent:
      role: "master_coordinator"
      authority_level: "executive"
      can_delegate_to: ["all_agents"]
      approval_authority: true
      context_management: true
    
    initialization_coordinator:
      role: "specialized_coordinator" 
      authority_level: "managerial"
      can_delegate_to: ["analysis_agents", "synthesis_agents"]
      approval_authority: false
      context_management: true
    
    analysis_agents:
      role: "specialist"
      authority_level: "individual_contributor"
      can_delegate_to: []
      approval_authority: false
      context_management: false
  
  # Sequential coordination for spec generation
  sequential:
    phase_order:
      - requirements_agent
      - design_agent
      - tasks_agent
      - implementation_agent
    
    phase_dependencies:
      requirements_agent: []
      design_agent: ["requirements_agent"]
      tasks_agent: ["design_agent"]
      implementation_agent: ["tasks_agent"]
    
    handoff_requirements:
      - complete_deliverable
      - validate_quality_gates
      - preserve_context
      - update_traceability

# Communication protocols
communication:
  context_sharing:
    method: "mcp_continuity"
    session_persistence: true
    cross_agent_memory: true
    pattern_storage: true
  
  status_reporting:
    frequency: "phase_completion"
    format: "structured_json"
    include_metrics: true
    escalation_triggers:
      - "quality_gate_failure"
      - "timeout_exceeded" 
      - "validation_failure"
  
  approval_gates:
    human_approval_required: true
    approval_timeout: 24  # hours
    escalation_on_timeout: true
    approval_delegation: false

# Quality coordination
quality_assurance:
  peer_review:
    enabled: true
    reviewer_assignment: "automatic"
    minimum_reviewers: 1
  
  validation_coordination:
    cross_validate_outputs: true
    consistency_checks: true
    traceability_validation: true
  
  feedback_loops:
    implementation_to_design: true
    design_to_requirements: true
    continuous_improvement: true

# Error handling coordination
error_handling:
  escalation_hierarchy:
    level_1: "peer_agents"
    level_2: "coordinator_agent"
    level_3: "orchestrator_agent"
    level_4: "human_intervention"
  
  recovery_strategies:
    context_loss: "restore_from_mcp"
    validation_failure: "iterate_with_feedback"
    timeout: "checkpoint_and_resume"
    agent_failure: "delegate_to_backup"
  
  learning_from_errors:
    pattern_updates: true
    process_improvements: true
    agent_training_updates: false

# Performance coordination
performance:
  parallel_execution:
    analysis_phase: true
    synthesis_phase: false
    validation_checks: true
  
  resource_management:
    context_window_optimization: true
    token_usage_monitoring: true
    memory_efficient_handoffs: true
  
  optimization_strategies:
    batched_operations: true
    cached_responses: true
    incremental_processing: true