# Quality Gates Configuration
# Defines validation criteria and approval requirements for each workflow phase

quality_gates:
  
  # Requirements Phase Quality Gate
  requirements_phase:
    gate_name: "Requirements Validation Gate"
    mandatory: true
    approval_required: true
    
    validation_criteria:
      syntax_validation:
        description: "All requirements follow EARS syntax"
        validator: "ears_syntax_validator"
        threshold: 100
        critical: true
      
      completeness_check:
        description: "All functional and non-functional requirements covered"
        validator: "completeness_validator"
        threshold: 95
        critical: true
      
      testability_assessment:
        description: "All requirements are testable and measurable"
        validator: "testability_validator"
        threshold: 90
        critical: true
      
      consistency_validation:
        description: "No conflicting or contradictory requirements"
        validator: "consistency_validator"
        threshold: 100
        critical: true
      
      traceability_check:
        description: "Requirements traceable to original request"
        validator: "traceability_validator"
        threshold: 100
        critical: true
    
    approval_criteria:
      stakeholder_review: true
      business_alignment: true
      technical_feasibility: true
      security_consideration: true
    
    deliverables_required:
      - "requirements.md"
      - "acceptance_criteria.md"
      - "metadata.json"
  
  # Design Phase Quality Gate
  design_phase:
    gate_name: "Design Validation Gate"
    mandatory: true
    approval_required: true
    
    validation_criteria:
      architecture_completeness:
        description: "Complete architectural design with all components"
        validator: "architecture_validator"
        threshold: 95
        critical: true
      
      api_specification:
        description: "Complete API contracts and data models"
        validator: "api_validator"
        threshold: 90
        critical: true
      
      security_design:
        description: "Security considerations addressed"
        validator: "security_validator"
        threshold: 85
        critical: true
      
      integration_design:
        description: "Integration points clearly defined"
        validator: "integration_validator"
        threshold: 90
        critical: false
      
      diagram_quality:
        description: "Mermaid diagrams are valid and informative"
        validator: "diagram_validator"
        threshold: 85
        critical: false
      
      requirements_traceability:
        description: "All requirements addressed in design"
        validator: "requirements_coverage_validator"
        threshold: 100
        critical: true
    
    approval_criteria:
      technical_review: true
      architecture_alignment: true
      scalability_consideration: true
      maintainability_assessment: true
    
    deliverables_required:
      - "design.md"
      - "architecture_diagrams"
      - "api_specifications"
      - "data_models"
      - "updated_metadata.json"
  
  # Tasks Phase Quality Gate
  tasks_phase:
    gate_name: "Implementation Planning Gate"
    mandatory: true
    approval_required: true
    
    validation_criteria:
      task_granularity:
        description: "Tasks are appropriately sized (4-8 hours)"
        validator: "granularity_validator"
        threshold: 90
        critical: true
      
      dependency_mapping:
        description: "Task dependencies clearly identified"
        validator: "dependency_validator"
        threshold: 95
        critical: true
      
      design_coverage:
        description: "All design elements covered by tasks"
        validator: "coverage_validator"
        threshold: 100
        critical: true
      
      estimation_quality:
        description: "Realistic effort estimates provided"
        validator: "estimation_validator"
        threshold: 80
        critical: false
      
      completion_criteria:
        description: "Clear completion criteria for each task"
        validator: "criteria_validator"
        threshold: 100
        critical: true
      
      risk_assessment:
        description: "Technical risks identified and mitigated"
        validator: "risk_validator"
        threshold: 85
        critical: false
    
    approval_criteria:
      implementation_feasibility: true
      resource_availability: true
      timeline_realism: true
      quality_standards_alignment: true
    
    deliverables_required:
      - "tasks.md"
      - "implementation_plan"
      - "risk_assessment"
      - "updated_metadata.json"
  
  # Implementation Phase Quality Gate
  implementation_phase:
    gate_name: "Code Quality Gate"
    mandatory: true
    approval_required: true
    
    validation_criteria:
      code_quality:
        description: "Code meets quality standards"
        validator: "code_quality_validator"
        threshold: 85
        critical: true
      
      test_coverage:
        description: "Minimum test coverage achieved"
        validator: "test_coverage_validator"
        threshold: 90
        critical: true
      
      security_compliance:
        description: "Security standards compliance"
        validator: "security_compliance_validator"
        threshold: 100
        critical: true
      
      documentation_completeness:
        description: "Code and API documentation complete"
        validator: "documentation_validator"
        threshold: 85
        critical: false
      
      integration_testing:
        description: "Integration tests pass"
        validator: "integration_test_validator"
        threshold: 100
        critical: true
      
      requirements_fulfillment:
        description: "All requirements implemented and tested"
        validator: "requirements_fulfillment_validator"
        threshold: 100
        critical: true
    
    approval_criteria:
      functional_testing_passed: true
      non_functional_requirements_met: true
      code_review_completed: true
      deployment_readiness: true
    
    deliverables_required:
      - "source_code"
      - "test_suites"
      - "documentation"
      - "deployment_scripts"
      - "final_metadata.json"

# Human Approval Configuration
human_approval:
  timeout_policy:
    default_timeout: 24  # hours
    escalation_after: 48  # hours
    auto_reject_after: 72  # hours
  
  approval_delegation:
    enabled: false
    delegation_hierarchy: []
  
  feedback_requirements:
    structured_feedback: true
    improvement_suggestions: true
    approval_reasoning: true
  
  bypass_conditions:
    emergency_release: false
    hotfix_deployment: false
    security_patch: false

# Automated Validation
automated_validation:
  parallel_execution: true
  fail_fast: true
  detailed_reporting: true
  
  custom_validators:
    ears_syntax_validator:
      script: "validators/ears_syntax.py"
      timeout: 30
    
    architecture_validator:
      script: "validators/architecture_check.py"
      timeout: 60
    
    security_validator:
      script: "validators/security_check.py"
      timeout: 120

# Quality Metrics
quality_metrics:
  gate_success_rate: true
  average_approval_time: true
  validation_failure_patterns: true
  improvement_trends: true
  
  reporting:
    frequency: "weekly"
    dashboard_enabled: true
    stakeholder_notifications: true